### ISSUE TITLE
ImageQueueLoop closes on own

### ISSUE THREAD

**Issue by MaleNurse** [VorlonCD/bi-aidetection#160]
OS: Win10Pro 20H2
AITOOL: 25.0.627.7696

I've had the ImageQueueLoop close on me a couple times now, possibly randomly, possibly when I clean up the image folder that the program is monitoring. The problems starts with the relevant log showing `------Closing------- CloseReason: UserClosing|28388|1||1`, a JSON save, and then `ImageQueueLoop canceled.` After that the queue just keeps building up until it hits max and starts throwing errors. Nothing precedes this in the log except for successfully processing images from the queue.

Attached is today's log. The problem hits at  07:17:17 (not so lucky I guess). Please let me know if there is anything you need.
[AITool.[2021-02-02].log](https://github.com/VorlonCD/bi-aidetection/files/5914789/AITool.2021-02-02.log)

**Comment by VorlonCD** [comment]
If you close the program but say NO when asked if sure, that would cause that issue.
Fixed for next version.

**Comment by MaleNurse** [comment]
Well, I certainly  have done that, absentmindedly, a couple times. Thank you for your work!

**Comment by VorlonCD** [comment]
This should prevent that issue:
[AITool-VorlonCD-v2.0.700.zip](https://github.com/VorlonCD/bi-aidetection/files/5978621/AITool-VorlonCD-v2.0.700.zip)

**Comment by MaleNurse** [comment]
So far, so good! I still get the `CloseReason: UserClosing` event in the log before cancelling but now it continues to process images added to the queue. And given that it's an "Info" level event, I imagine that's just logging the fact that my dumb ass clicked the button again.

Thanks for the fix!
